server:
  port: 8765
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health    
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

  